Repository opendatateam/udata-front-kit, pull requests merged in 2023-11, with the labels that each got.

#141 feat(api): add & test delete
  package-lock.json
  package.json
  src/components/ChartData.vue
  src/services/api/DatagouvfrAPI.js
  src/services/api/__tests__/DatagouvfrAPI.test.js
Labels: enhancement

#110 feat(bouquet): crée un bouquet avec thématique, chantier, et datasets
  configs/ecospheres/config.yaml
  src/assets/main.css
  src/components/Tooltip.vue
  src/store/TopicStore.js
  src/views/bouquets/BouquetDetailView.vue
  src/views/bouquets/BouquetEditView.vue
Labels: enhancement

#162 build(npm): enable typescript
  .eslintrc.js
  package-lock.json
  package.json
  tsconfig.eslint.json
Labels: enhancement

#156 feat(nav): filter themes
  .gitignore
  configs/ecospheres/config.yaml
  package.json
  src/assets/main.css
  src/components/HomeThemes.vue
  src/model.ts
  src/services/api/__tests__/DatagouvfrAPI.test.js
  src/views/HomeView.vue
Labels: enhancement

#161 feat(bouquet): crée bouquet avec donnée non-disponible/manquante
  configs/ecospheres/config.yaml
  package.json
  src/assets/main.css
  src/components/Tooltip.vue
  src/views/bouquets/BouquetDetailView.vue
  src/views/bouquets/BouquetEditView.vue
Labels: enhancement

#170 build(npm): type checks
  .eslintrc.js
  README.md
  package-lock.json
  package.json
  tsconfig.dev.json
  tsconfig.eslint.json
  tsconfig.json
  vite.config.ts
Labels: feat

#143 policy: traduit les templates github en FR
  .github/ISSUE_TEMPLATE.md
  .github/PULL_REQUEST_TEMPLATE.md
Labels: feat

#171 fix(bouquet): addresse le loader infini
  package-lock.json
  package.json
  src/components/HomeThemes.vue
  src/composables/__tests__/loader.test.js
  src/composables/__tests__/test-item-with-loader.vue
  src/composables/loader.ts
  src/store/TopicStore.js
  src/views/bouquets/BouquetsListView.vue
  tsconfig.dev.json
  vite.config.ts
Labels: fix

#192 build(vite): add vite esm bundler
  vite.config.ts
Labels: build

#189 build: fix typescript in vscode
  .vscode/extensions.json
  package-lock.json
  package.json
  tsconfig.dev.json
  tsconfig.json
  vite.config.ts
Labels: build

#197 build(npm): disable --fix from eslint
  package.json
Labels: build

#198 build(npm): fix husky et applique format
  .github/workflows/node.js.yml
  package.json
  src/views/bouquets/BouquetEditView.vue
Labels: build

#176 feat(bouquet): visualisation d'un bouquet
  configs/ecospheres/config.yaml
  src/views/bouquets/BouquetDetailView.vue
Labels: feat

#202 ADR: change schéma pour trame de bouquet
  docs/architecture-decisions/1-change-schema-pour-trame-de-bouquet.md
  docs/requests-for-comments/1-changer-le-nom-schema-de-bouquet.md
Labels: a/ddr

#184 feat: colored banner in homepage
  configs/ecospheres/config.yaml
  configs/meteo-france/config.yaml
  src/App.vue
  src/views/AboutView.vue
  src/views/HomeView.vue
  src/views/LoginView.vue
  src/views/LogoutView.vue
  src/views/SimplePageView.vue
  src/views/bouquets/BouquetDetailView.vue
  src/views/bouquets/BouquetEditView.vue
  src/views/bouquets/BouquetsListView.vue
  src/views/datasets/DatasetDetailView.vue
  src/views/datasets/DatasetsListView.vue
  src/views/organizations/OrganizationDetailView.vue
  src/views/organizations/OrganizationsListView.vue
Labels: feat

#186 feat: style home topics
  configs/meteo-france/config.yaml
  src/components/HomeTopics.vue
Labels: feat

#187 feat: allow secondary search rerouting to another page
  configs/ecospheres/config.yaml
  configs/meteo-france/config.yaml
  src/views/HomeView.vue
Labels: feat

#203 ci: rajoute `npm clean-install` dans le README.md
  .nvmrc
  README.md
  package-lock.json
Labels: ci
