Repository opendatateam/udata-front-kit, pull requests merged in 2023-10, with the labels that each got.

#59 Add issue and pull request template
  .github/ISSUE_TEMPLATE.md
  .github/PULL_REQUEST_TEMPLATE.md
  .gitignore
Labels: documentation

#98 chore(policy): add a CONTRIBUTING.md file
  CONTRIBUTING.md
  package-lock.json
  package.json
Labels: documentation, discuss

#94 feat(bouquet): create bouquet
  package-lock.json
  src/components/Tooltip.vue
  src/services/api/DatagouvfrAPI.js
  src/views/bouquets/BouquetEditView.vue
Labels: enhancement
